import type {
  AdminRole,
  AdminUser,
  Announcement,
  AnnouncementStatus,
  ApprovalPromotion,
  ApprovalStatus,
  BankConfig,
  Brand,
  BrandProduct,
  CountryConfig,
  Customer,
  DiscountType,
  Distributor,
  DistributorStatus,
  EmailTemplateRecord,
  Order,
  Payout,
  PayoutAffiliateSummary,
  PayoutGroup,
  PayoutStatus,
  Product,
  ProductPromotion,
  ProfileTab,
  PromotionStatus,
  RegistrationApproval,
  ShippingStatus,
  User,
} from "@/components/type";

// --- Orders ---

export const SHIPPING_STATUS_CONFIG: Record<
  ShippingStatus,
  { label: string; dotColor: string }
> = {
  shipped: { label: "Shipped", dotColor: "#51C712" },
  preparing: { label: "Preparing", dotColor: "#FFC300" },
  in_transit: { label: "In Transit", dotColor: "#00A1FF" },
  refunded: { label: "Refunded", dotColor: "#FF0000" },
  completed: { label: "Completed", dotColor: "#6b7280" },
};

export const SHIPPING_STATUS_OPTIONS = [
  { label: "All", value: "all" },
  { label: "Shipped", value: "shipped" },
  { label: "Preparing", value: "preparing" },
  { label: "In Transit", value: "in_transit" },
  { label: "Refunded", value: "refunded" },
  { label: "Completed", value: "completed" },
];

export const ORDERS: Order[] = [
  {
    id: "OR-00241",
    orderedDate: "2026-03-12",
    customerName: "Theresa Webb",
    customerId: "#CU8932",
    orderItems: 3,
    shippingStatus: "completed",
    totalSales: "$15,200",
    commission: "$1,520",
    referralMemberName: "Sarah Chen",
    referralMemberId: "#AG8932",
    totalCommission: "$3,040",
  },
  {
    id: "OR-00242",
    orderedDate: "2026-03-15",
    customerName: "Jenny Wilson",
    customerId: "#CU3761",
    orderItems: 1,
    shippingStatus: "in_transit",
    totalSales: "$4,100",
    commission: "$410",
    referralMemberName: "Anan Suksan",
    referralMemberId: "#AG3761",
    totalCommission: "$820",
  },
  {
    id: "OR-00243",
    orderedDate: "2026-03-18",
    customerName: "Ralph Edwards",
    customerId: "#CU6145",
    orderItems: 2,
    shippingStatus: "preparing",
    totalSales: "$1,100",
    commission: "$110",
    referralMemberName: "Nur Aisyah",
    referralMemberId: "#AG6145",
    totalCommission: "$220",
  },
  {
    id: "OR-00244",
    orderedDate: "2026-03-20",
    customerName: "Marvin McKinney",
    customerId: "#CU9892",
    orderItems: 5,
    shippingStatus: "shipped",
    totalSales: "$30",
    commission: "$3",
    referralMemberName: "Wei Ming",
    referralMemberId: "#AG9892",
    totalCommission: "$6",
  },
  {
    id: "OR-00245",
    orderedDate: "2026-03-22",
    customerName: "Brooklyn Simmons",
    customerId: "#CU9735",
    orderItems: 1,
    shippingStatus: "refunded",
    totalSales: "$1,100",
    commission: "$0",
    referralMemberName: "Zhi Hao",
    referralMemberId: "#AG9735",
    totalCommission: "$0",
  },
  {
    id: "OR-00246",
    orderedDate: "2026-03-25",
    customerName: "Albert Flores",
    customerId: "#CU4719",
    orderItems: 2,
    shippingStatus: "completed",
    totalSales: "$820",
    commission: "$82",
    referralMemberName: "Sarah Chen",
    referralMemberId: "#AG8932",
    totalCommission: "$164",
  },
];

// --- Customers ---

export const COUNTRY_NAMES: Record<string, string> = {
  SG: "Singapore",
  TH: "Thailand",
  MY: "Malaysia",
  ID: "Indonesia",
  VN: "Vietnam",
  PH: "Philippines",
};

export const CUSTOMERS: Customer[] = [
  {
    name: "Theresa Webb",
    code: "#CU8932",
    country: "SG",
    email: "theresa.webb@example.com",
    phone: "+65 91234567",
    lastOrderDate: "2026-03-12",
    totalSales: "$15,200",
    totalCommission: "$3,040",
    myCommission: "$1,520",
    referralMemberName: "Sarah Chen",
    referralMemberId: "#AG8932",
  },
  {
    name: "Jenny Wilson",
    code: "#CU3761",
    country: "TH",
    email: "jenny.wilson@example.com",
    phone: "+66 812345678",
    lastOrderDate: "2026-03-15",
    totalSales: "$4,100",
    totalCommission: "$820",
    myCommission: "$410",
    referralMemberName: "Anan Suksan",
    referralMemberId: "#AG3761",
  },
  {
    name: "Ralph Edwards",
    code: "#CU6145",
    country: "MY",
    email: "ralph.edwards@example.com",
    phone: "+60 123456789",
    lastOrderDate: "2026-03-18",
    totalSales: "$1,100",
    totalCommission: "$220",
    myCommission: "$110",
    referralMemberName: "Nur Aisyah",
    referralMemberId: "#AG6145",
  },
  {
    name: "Marvin McKinney",
    code: "#CU9892",
    country: "SG",
    email: "marvin.mckinney@example.com",
    phone: "+65 98765432",
    lastOrderDate: "2026-03-20",
    totalSales: "$30",
    totalCommission: "$6",
    myCommission: "$3",
    referralMemberName: "Wei Ming",
    referralMemberId: "#AG9892",
  },
  {
    name: "Brooklyn Simmons",
    code: "#CU9735",
    country: "ID",
    email: "brooklyn.simmons@example.com",
    phone: "+62 81234567890",
    lastOrderDate: "2026-03-22",
    totalSales: "$1,100",
    totalCommission: "$220",
    myCommission: "$110",
    referralMemberName: "Zhi Hao",
    referralMemberId: "#AG9735",
  },
  {
    name: "Albert Flores",
    code: "#CU4719",
    country: "VN",
    email: "albert.flores@example.com",
    phone: "+84 901234567",
    lastOrderDate: "2026-03-25",
    totalSales: "$820",
    totalCommission: "$164",
    myCommission: "$82",
    referralMemberName: "Sarah Chen",
    referralMemberId: "#AG8932",
  },
];

// --- Email templates ---

export const EMAIL_TEMPLATES: EmailTemplateRecord[] = [
  {
    id: "ET-00101",
    name: "Welcome & Onboarding",
    title: "Welcome to Aim Earn 👋",
    content:
      "Hi {{name}},\n\nWelcome aboard! We're thrilled to have you. This email walks you through your first steps as a new member of the program.",
    promotionId: undefined,
    updatedDate: "2026-03-05",
  },
  {
    id: "ET-00102",
    name: "Spring Promotion",
    title: "Your spring savings are here",
    content:
      "Spring is here — and so are the deals. Enjoy 20% off StellarTech ANC Headphones this month only, with free shipping across SG.",
    promotionId: "PR-001",
    updatedDate: "2026-03-18",
  },
  {
    id: "ET-00103",
    name: "Monthly Newsletter Digest",
    title: "Your monthly roundup",
    content:
      "Here's what happened this month: new products, featured creators, and the top-earning promotions across the network.",
    promotionId: undefined,
    updatedDate: "2026-03-30",
  },
  {
    id: "ET-00104",
    name: "Abandoned Cart Reminder",
    title: "You left something behind",
    content:
      "We saved your cart for 48 hours. Tap below to finish checking out before the promo ends.",
    promotionId: "PR-006",
    updatedDate: "2026-04-02",
  },
  {
    id: "ET-00105",
    name: "Order Confirmation",
    title: "Order received — thanks!",
    content:
      "We've received your order and are preparing it for shipment. You'll get another email with tracking once it ships.",
    promotionId: undefined,
    updatedDate: "2026-04-10",
  },
  {
    id: "ET-00106",
    name: "Post-Purchase Thank You",
    title: "Thanks for shopping with us",
    content:
      "Thanks again for your order. If you have a moment, leave a quick review — your feedback helps other shoppers decide.",
    promotionId: "PR-004",
    updatedDate: "2026-04-14",
  },
];

// --- Products ---

export const PRODUCTS: Product[] = [
  {
    sku: "SKU-HEADPHONE-001",
    name: "Quantum Pro X",
    brand: "StellarTech",
    price: "$23.99",
    thumbnail: "https://placehold.co/80x80?text=QP",
    shareUrl: "https://shop.example.com/p/SKU-HEADPHONE-001?ref=XX0025",
    countries: ["SG", "TH", "MY", "ID"],
    status: "active",
    updatedBy: "Ethan Quantum",
    updatedDate: "2026-01-12",
  },
  {
    sku: "SKU-HEADPHONE-002",
    name: "NovaTech Ultra",
    brand: "NovaGlow",
    price: "$19.50",
    thumbnail: "https://placehold.co/80x80?text=NT",
    shareUrl: "https://shop.example.com/p/SKU-HEADPHONE-002?ref=XX0025",
    countries: ["SG"],
    status: "active",
    updatedBy: "Luna Nova",
    updatedDate: "2026-01-01",
  },
  {
    sku: "SKU-HEADPHONE-003",
    name: "Apex Prime Elite",
    brand: "ZenithCorp",
    price: "$45.00",
    thumbnail: "https://placehold.co/80x80?text=AP",
    shareUrl: "https://shop.example.com/p/SKU-HEADPHONE-003?ref=XX0025",
    countries: ["SG"],
    status: "active",
    updatedBy: "Ava Apex",
    updatedDate: "2025-12-15",
  },
  {
    sku: "SKU-HEADPHONE-004",
    name: "Zenith Max Plus",
    brand: "AquaLeap",
    price: "$120.00",
    thumbnail: "https://placehold.co/80x80?text=ZM",
    shareUrl: "https://shop.example.com/p/SKU-HEADPHONE-004?ref=XX0025",
    countries: ["SG"],
    status: "active",
    updatedBy: "Zara Zenith",
    updatedDate: "2025-11-03",
  },
  {
    sku: "SKU-HEADPHONE-005",
    name: "Stellar Edge Pro",
    brand: "Veridian Dynamics",
    price: "$77.50",
    thumbnail: "https://placehold.co/80x80?text=SE",
    shareUrl: "https://shop.example.com/p/SKU-HEADPHONE-005?ref=XX0025",
    countries: ["SG"],
    status: "active",
    updatedBy: "Leo Stellar",
    updatedDate: "2025-10-22",
  },
  {
    sku: "SKU-HEADPHONE-006",
    name: "Fusion Core X",
    brand: "Solaris Innovations",
    price: "$240.00",
    thumbnail: "https://placehold.co/80x80?text=FC",
    shareUrl: "https://shop.example.com/p/SKU-HEADPHONE-006?ref=XX0025",
    countries: ["SG"],
    status: "active",
    updatedBy: "Maya Fusion",
    updatedDate: "2025-09-07",
  },
  {
    sku: "SKU-HEADPHONE-007",
    name: "Velocity Prime Max",
    brand: "CrimsonTide",
    price: "$99.99",
    thumbnail: "https://placehold.co/80x80?text=VP",
    shareUrl: "https://shop.example.com/p/SKU-HEADPHONE-007?ref=XX0025",
    countries: ["SG"],
    status: "active",
    updatedBy: "Max Velocity",
    updatedDate: "2025-08-18",
  },
  {
    sku: "SKU-HEADPHONE-008",
    name: "Titan Edge Ultra",
    brand: "EmberCore",
    price: "$14.00",
    thumbnail: "https://placehold.co/80x80?text=TE",
    shareUrl: "https://shop.example.com/p/SKU-HEADPHONE-008?ref=XX0025",
    countries: ["SG"],
    status: "active",
    updatedBy: "Tessa Titan",
    updatedDate: "2025-08-18",
  },
  {
    sku: "SKU-HEADPHONE-009",
    name: "Omega Pro Elite",
    brand: "FrostPeak",
    price: "$150.50",
    thumbnail: "https://placehold.co/80x80?text=OP",
    shareUrl: "https://shop.example.com/p/SKU-HEADPHONE-009?ref=XX0025",
    countries: ["SG"],
    status: "active",
    updatedBy: "Owen Omega",
    updatedDate: "2025-07-30",
  },
  {
    sku: "SKU-HEADPHONE-010",
    name: "Aurora Max Plus",
    brand: "AzureWave",
    price: "$300.00",
    thumbnail: "https://placehold.co/80x80?text=AM",
    shareUrl: "https://shop.example.com/p/SKU-HEADPHONE-010?ref=XX0025",
    countries: ["SG"],
    status: "active",
    updatedBy: "Aria Aurora",
    updatedDate: "2025-07-30",
  },
];

export const DISCOUNT_TYPE_OPTIONS: { label: string; value: DiscountType }[] = [
  { label: "Percentage (%)", value: "percentage" },
  { label: "Amount ($)", value: "amount" },
];

export const STATUS_CONFIG: Record<
  PromotionStatus,
  { label: string; dotColor: string }
> = {
  draft: { label: "Draft", dotColor: "#00A1FF" },
  under_review: { label: "Under Review", dotColor: "#FFC300" },
  approved: { label: "Approved", dotColor: "#51C712" },
  published: { label: "Published", dotColor: "#E400F5" },
  rejected: { label: "Rejected", dotColor: "#FF0000" },
  expired: { label: "Expired", dotColor: "#ADADAD" },
};

export const PROMOTIONS: ProductPromotion[] = [
  {
    id: "PR-001",
    thumbnail: "https://placehold.co/80x80?text=HP",
    thumbnailName: "spring-sale-headphones.png",
    thumbnailSize: "1.2 MB",
    name: "Spring Sale 20% Off",
    description:
      "Site-wide spring promotion offering 20% off the StellarTech ANC Headphones. Runs March 15 through April 30. Affiliates earn standard commission plus a 2% bonus tier on converted orders.",
    productId: "SKU-HEADPHONE-001",
    productName: "StellarTech ANC Headphones",
    brand: "StellarTech",
    country: "SG",
    periodStart: "2026-03-15",
    periodEnd: "2026-04-30",
    discountType: "percentage",
    discountValue: 20,
    status: "published",
  },
  {
    id: "PR-002",
    thumbnail: "https://placehold.co/80x80?text=EB",
    thumbnailName: "early-bird-earbuds.jpg",
    thumbnailSize: "842 KB",
    name: "Early Bird Deal",
    description:
      "Limited-time 15% off for the first 500 buyers of the Pro Earbuds. Auto-applies at checkout when stock lasts.",
    productId: "SKU-EARBUDS-014",
    productName: "StellarTech Pro Earbuds",
    brand: "StellarTech",
    country: "TH",
    periodStart: "2026-02-01",
    periodEnd: "2026-02-28",
    discountType: "percentage",
    discountValue: 15,
    status: "expired",
  },
  {
    id: "PR-003",
    thumbnail: "https://placehold.co/80x80?text=SP",
    thumbnailName: "bundle-save-speaker.png",
    thumbnailSize: "2.4 MB",
    name: "Bundle & Save",
    description:
      "Buy a Bluetooth Speaker with any audio accessory and get 10% off the bundle. Stackable with member discounts up to a max of 15%.",
    productId: "SKU-SPEAKER-007",
    productName: "AquaSound Bluetooth Speaker",
    brand: "AquaSound",
    country: "MY",
    periodStart: "2026-05-01",
    periodEnd: "2026-05-31",
    discountType: "percentage",
    discountValue: 10,
    status: "under_review",
  },
  {
    id: "PR-004",
    thumbnail: "https://placehold.co/80x80?text=WT",
    thumbnailName: "fitness-month-watch.png",
    thumbnailSize: "3.1 MB",
    name: "Fitness Month",
    description:
      "A month-long campaign highlighting the Nimbus Fitness Watch. Includes creator bundle kits and extra affiliate training resources.",
    productId: "SKU-WATCH-032",
    productName: "Nimbus Fitness Watch",
    brand: "Nimbus",
    country: "SG",
    periodStart: "2026-04-10",
    periodEnd: "2026-05-10",
    discountType: "amount",
    discountValue: 25,
    status: "approved",
  },
  {
    id: "PR-005",
    thumbnail: "https://placehold.co/80x80?text=CM",
    thumbnailName: "launch-promo-camera.jpg",
    thumbnailSize: "1.8 MB",
    name: "Launch Promo",
    description:
      "Launch discount for the new Orbit 4K Action Camera. Early adopters receive an extended warranty plus a free accessory pack.",
    productId: "SKU-CAMERA-021",
    productName: "Orbit 4K Action Camera",
    brand: "Orbit",
    country: "ID",
    periodStart: "2026-06-01",
    periodEnd: "2026-06-30",
    discountType: "amount",
    discountValue: 50,
    status: "draft",
  },
  {
    id: "PR-006",
    thumbnail: "https://placehold.co/80x80?text=CM",
    thumbnailName: "weekend-flash-camera.gif",
    thumbnailSize: "540 KB",
    name: "Weekend Flash",
    description:
      "72-hour weekend flash sale on the 4K Action Camera. Inventory is capped; orders are first-come, first-served.",
    productId: "SKU-CAMERA-021",
    productName: "Orbit 4K Action Camera",
    brand: "Orbit",
    country: "VN",
    periodStart: "2026-03-20",
    periodEnd: "2026-03-22",
    discountType: "percentage",
    discountValue: 30,
    status: "rejected",
  },
];

export const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export const COUNTRY_OPTIONS = [
  { label: "All Countries", value: "all" },
  { label: "Singapore", value: "SG" },
  { label: "Thailand", value: "TH" },
  { label: "Malaysia", value: "MY" },
  { label: "Indonesia", value: "ID" },
  { label: "Vietnam", value: "VN" },
];

export const STATUS_OPTIONS = [
  { label: "All", value: "all" },
  { label: "Draft", value: "draft" },
  { label: "Under Review", value: "under_review" },
  { label: "Approved", value: "approved" },
  { label: "Published", value: "published" },
  { label: "Rejected", value: "rejected" },
  { label: "Expired", value: "expired" },
];

// --- Approval promotions ---

export const APPROVAL_STATUS_CONFIG: Record<
  ApprovalStatus,
  { label: string; dotColor: string }
> = {
  pending: { label: "Pending", dotColor: "#FFC300" },
  approved: { label: "Approved", dotColor: "#51C712" },
  rejected: { label: "Rejected", dotColor: "#FF0000" },
};

export const APPROVAL_STATUS_OPTIONS = [
  { label: "All", value: "all" },
  { label: "Pending", value: "pending" },
  { label: "Approved", value: "approved" },
  { label: "Rejected", value: "rejected" },
];

export const APPROVAL_PROMOTIONS: ApprovalPromotion[] = [
  {
    id: "PR-A-001",
    thumbnail: "https://placehold.co/80x80?text=HP",
    thumbnailName: "spring-sale-headphones.png",
    thumbnailSize: "1.2 MB",
    name: "Spring Sale 20% Off",
    description:
      "Site-wide spring promotion offering 20% off the StellarTech ANC Headphones. Runs March 15 through April 30. Affiliates earn standard commission plus a 2% bonus tier on converted orders.",
    productId: "SKU-HEADPHONE-001",
    productName: "StellarTech ANC Headphones",
    countries: ["SG", "MY", "TH"],
    periodStart: "2026-03-15",
    periodEnd: "2026-04-30",
    discountType: "percentage",
    discountValue: 20,
    requestedDate: "2026-03-04",
    requester: { name: "Dana Wong", code: "#DS1024" },
    status: "pending",
  },
  {
    id: "PR-A-002",
    thumbnail: "https://placehold.co/80x80?text=EB",
    thumbnailName: "early-bird-earbuds.jpg",
    thumbnailSize: "842 KB",
    name: "Early Bird Deal",
    description:
      "Limited-time 15% off for the first 500 buyers of the Pro Earbuds. Auto-applies at checkout while stock lasts.",
    productId: "SKU-EARBUDS-014",
    productName: "StellarTech Pro Earbuds",
    countries: ["TH"],
    periodStart: "2026-02-01",
    periodEnd: "2026-02-28",
    discountType: "percentage",
    discountValue: 15,
    requestedDate: "2026-01-18",
    requester: { name: "Marcus Lim", code: "#DS0871" },
    status: "approved",
    reviewer: { name: "Morgan Lee", code: "#AD0001" },
    reviewedDate: "2026-01-22",
  },
  {
    id: "PR-A-003",
    thumbnail: "https://placehold.co/80x80?text=SP",
    thumbnailName: "bundle-save-speaker.png",
    thumbnailSize: "2.4 MB",
    name: "Bundle & Save",
    description:
      "Buy a Bluetooth Speaker with any audio accessory and get 10% off the bundle. Stackable with member discounts up to a max of 15%.",
    productId: "SKU-SPEAKER-007",
    productName: "AquaSound Bluetooth Speaker",
    countries: ["MY", "ID"],
    periodStart: "2026-05-01",
    periodEnd: "2026-05-31",
    discountType: "percentage",
    discountValue: 10,
    requestedDate: "2026-04-10",
    requester: { name: "Priya Shah", code: "#DS0612" },
    status: "pending",
  },
  {
    id: "PR-A-004",
    thumbnail: "https://placehold.co/80x80?text=WT",
    thumbnailName: "fitness-month-watch.png",
    thumbnailSize: "3.1 MB",
    name: "Fitness Month",
    description:
      "A month-long campaign highlighting the Nimbus Fitness Watch. Includes creator bundle kits and extra affiliate training resources.",
    productId: "SKU-WATCH-032",
    productName: "Nimbus Fitness Watch",
    countries: ["SG"],
    periodStart: "2026-04-10",
    periodEnd: "2026-05-10",
    discountType: "amount",
    discountValue: 25,
    requestedDate: "2026-03-22",
    requester: { name: "Haruto Sato", code: "#DS0455" },
    status: "approved",
    reviewer: { name: "Morgan Lee", code: "#AD0001" },
    reviewedDate: "2026-03-26",
  },
  {
    id: "PR-A-005",
    thumbnail: "https://placehold.co/80x80?text=CM",
    thumbnailName: "weekend-flash-camera.gif",
    thumbnailSize: "540 KB",
    name: "Weekend Flash",
    description:
      "72-hour weekend flash sale on the 4K Action Camera. Inventory is capped; orders are first-come, first-served.",
    productId: "SKU-CAMERA-021",
    productName: "Orbit 4K Action Camera",
    countries: ["VN", "PH"],
    periodStart: "2026-03-20",
    periodEnd: "2026-03-22",
    discountType: "percentage",
    discountValue: 30,
    requestedDate: "2026-03-01",
    requester: { name: "Lena Pham", code: "#DS0339" },
    status: "rejected",
    reviewer: { name: "Morgan Lee", code: "#AD0001" },
    reviewedDate: "2026-03-05",
    rejectionReason:
      "Discount exceeds the 25% cap for flash events. Please resubmit at or below that threshold.",
  },
];

// --- Registration approvals ---

export const REGISTRATION_APPROVALS: RegistrationApproval[] = [
  {
    id: "RG-A-001",
    distributor: { name: "Dana Wong", code: "#DS1024" },
    email: "dana.wong@example.com",
    companyName: "Nova Retail Pte Ltd",
    taxId: "SG-202312345X",
    countries: ["SG", "MY"],
    countryPricing: [
      { country: "SG", price: 1500 },
      { country: "MY", price: 800 },
    ],
    totalAmount: "$2,530",
    requestedDate: "2026-03-12",
    paymentSlipUrl: "https://placehold.co/600x800?text=Slip+RG-A-001",
    paymentSlipName: "payment-slip-rg-a-001.png",
    paymentSlipSize: "1.1 MB",
    bank: {
      name: "DBS Bank",
      logoUrl: "https://placehold.co/80x40?text=K",
      swift: "DBSSSGSG",
      accountName: "Nova Retail Pte Ltd",
      accountNumber: "123-456-7890",
    },
    status: "pending",
  },
  {
    id: "RG-A-002",
    distributor: { name: "Marcus Lim", code: "#DS0871" },
    email: "marcus.lim@example.com",
    companyName: "Apex Trading Co.",
    taxId: "TH-0105567890123",
    currentCountries: ["SG"],
    countries: ["TH"],
    countryPricing: [{ country: "TH", price: 1100 }],
    totalAmount: "$1,210",
    requestedDate: "2026-02-22",
    paymentSlipUrl: "https://placehold.co/600x800?text=Slip+RG-A-002",
    paymentSlipName: "payment-slip-rg-a-002.png",
    paymentSlipSize: "742 KB",
    bank: {
      name: "Bangkok Bank",
      logoUrl: "https://placehold.co/80x40?text=B",
      swift: "BKKBTHBK",
      accountName: "Apex Trading Co.",
      accountNumber: "201-554-8821",
    },
    status: "approved",
    reviewer: { name: "Morgan Lee", code: "#AD0001" },
    reviewedDate: "2026-02-26",
  },
  {
    id: "RG-A-003",
    distributor: { name: "Priya Shah", code: "#DS0612" },
    email: "priya.shah@example.com",
    companyName: "Mandala Distribution",
    taxId: "MY-202201098765",
    countries: ["MY", "ID", "PH"],
    countryPricing: [
      { country: "MY", price: 2000 },
      { country: "ID", price: 1500 },
      { country: "PH", price: 900 },
    ],
    totalAmount: "$4,840",
    requestedDate: "2026-04-02",
    paymentSlipUrl: "https://placehold.co/600x800?text=Slip+RG-A-003",
    paymentSlipName: "payment-slip-rg-a-003.png",
    paymentSlipSize: "2.3 MB",
    bank: {
      name: "CIMB",
      logoUrl: "https://placehold.co/80x40?text=C",
      swift: "CIBBMYKL",
      accountName: "Mandala Distribution",
      accountNumber: "7012-4455-6677",
    },
    status: "pending",
  },
  {
    id: "RG-A-004",
    distributor: { name: "Haruto Sato", code: "#DS0455" },
    email: "haruto.sato@example.com",
    companyName: "Sato & Partners",
    taxId: "SG-202400876Y",
    currentCountries: ["TH", "MY"],
    countries: ["SG"],
    countryPricing: [{ country: "SG", price: 2700 }],
    totalAmount: "$2,970",
    requestedDate: "2026-03-28",
    paymentSlipUrl: "https://placehold.co/600x800?text=Slip+RG-A-004",
    paymentSlipName: "payment-slip-rg-a-004.png",
    paymentSlipSize: "1.8 MB",
    bank: {
      name: "OCBC Bank",
      logoUrl: "https://placehold.co/80x40?text=O",
      swift: "OCBCSGSG",
      accountName: "Sato & Partners",
      accountNumber: "555-773-2210",
    },
    status: "approved",
    reviewer: { name: "Morgan Lee", code: "#AD0001" },
    reviewedDate: "2026-04-01",
  },
  {
    id: "RG-A-005",
    distributor: { name: "Lena Pham", code: "#DS0339" },
    email: "lena.pham@example.com",
    companyName: "Pham Global",
    taxId: "VN-0312-898765",
    countries: ["VN"],
    countryPricing: [{ country: "VN", price: 820 }],
    totalAmount: "$902",
    requestedDate: "2026-03-06",
    paymentSlipUrl: "https://placehold.co/600x800?text=Slip+RG-A-005",
    paymentSlipName: "payment-slip-rg-a-005.png",
    paymentSlipSize: "1.8 MB",
    bank: {
      name: "Vietcombank",
      logoUrl: "https://placehold.co/80x40?text=V",
      swift: "BFTVVNVX",
      accountName: "Pham Global",
      accountNumber: "0071-000-228811",
    },
    status: "rejected",
    reviewer: { name: "Morgan Lee", code: "#AD0001" },
    reviewedDate: "2026-03-10",
    rejectionReason:
      "The payment slip amount does not match the requested total. Please upload a corrected slip and resubmit.",
  },
];

// --- Distributor roster (admin affiliate view) ---

export const DISTRIBUTOR_STATUS_CONFIG: Record<
  DistributorStatus,
  { label: string; dotColor: string }
> = {
  active: { label: "Active", dotColor: "#51C712" },
  inactive: { label: "Inactive", dotColor: "#ADADAD" },
};

export const DISTRIBUTOR_STATUS_OPTIONS = [
  { label: "All", value: "all" },
  { label: "Active", value: "active" },
  { label: "Inactive", value: "inactive" },
];

export const PROFILE_TAB_ITEMS: { value: ProfileTab; label: string }[] = [
  { value: "profile", label: "Profile" },
  { value: "affiliates", label: "Affiliates" },
  { value: "selling", label: "Selling" },
  { value: "buying", label: "Buying" },
  { value: "bank", label: "Bank Account" },
];

export const DISTRIBUTORS: Distributor[] = [
  {
    id: "#DS1024",
    name: "Dana Wong",
    email: "dana.wong@example.com",
    countries: ["SG", "MY", "TH", "ID"],
    affiliateMembers: 18240,
    joined: "2026-01-05",
    totalOrders: 12430,
    totalSales: "$820,452",
    commissionPool: "$82,045",
    directCommission: "$41,000",
    indirectCommission: "$24,600",
    totalEarnings: "$65,600",
    status: "active",
    bank: {
      name: "Kasikornbank",
      logoUrl: "https://placehold.co/24x24?text=K",
      swift: "KASITHBK",
      accountName: "Aimearn CO., LTD.",
      accountNumber: "123-4-56789-0",
    },
  },
  {
    id: "#DS0871",
    name: "Marcus Lim",
    email: "marcus.lim@example.com",
    countries: ["TH", "VN", "PH"],
    affiliateMembers: 14130,
    joined: "2026-01-12",
    totalOrders: 9870,
    totalSales: "$612,900",
    commissionPool: "$61,290",
    directCommission: "$30,500",
    indirectCommission: "$18,300",
    totalEarnings: "$48,800",
    status: "active",
    inviter: { name: "Sarah Chen", code: "#AG8932" },
    distributor: { name: "Dana Wong", code: "#DS1024" },
    bank: {
      name: "Bangkok Bank",
      logoUrl: "https://placehold.co/24x24?text=BBL",
      swift: "BKKBTHBK",
      accountName: "Apex Trading Co.",
      accountNumber: "201-554-8821",
    },
  },
  {
    id: "#DS0612",
    name: "Priya Shah",
    email: "priya.shah@example.com",
    countries: ["MY", "ID"],
    affiliateMembers: 11890,
    joined: "2026-02-01",
    totalOrders: 7420,
    totalSales: "$498,120",
    commissionPool: "$49,812",
    directCommission: "$24,900",
    indirectCommission: "$14,900",
    totalEarnings: "$39,800",
    status: "active",
    inviter: { name: "Anan Suksan", code: "#AG3761" },
    bank: {
      name: "CIMB",
      logoUrl: "https://placehold.co/24x24?text=CIMB",
      swift: "CIBBMYKL",
      accountName: "Mandala Distribution",
      accountNumber: "7012-4455-6677",
    },
  },
  {
    id: "#DS0455",
    name: "Haruto Sato",
    email: "haruto.sato@example.com",
    countries: ["SG"],
    affiliateMembers: 9720,
    joined: "2026-02-14",
    totalOrders: 5210,
    totalSales: "$401,560",
    commissionPool: "$40,156",
    directCommission: "$20,000",
    indirectCommission: "$12,000",
    totalEarnings: "$32,000",
    status: "inactive",
    inviter: { name: "Nur Aisyah", code: "#AG6145" },
    distributor: { name: "Priya Shah", code: "#DS0612" },
    bank: {
      name: "OCBC Bank",
      logoUrl: "https://placehold.co/24x24?text=OCBC",
      swift: "OCBCSGSG",
      accountName: "Sato & Partners",
      accountNumber: "555-773-2210",
    },
  },
  {
    id: "#DS0339",
    name: "Lena Pham",
    email: "lena.pham@example.com",
    countries: ["VN", "PH", "ID", "MY", "TH"],
    affiliateMembers: 8150,
    joined: "2026-02-28",
    totalOrders: 4120,
    totalSales: "$344,100",
    commissionPool: "$34,410",
    directCommission: "$17,200",
    indirectCommission: "$10,300",
    totalEarnings: "$27,500",
    status: "inactive",
    inviter: { name: "Wei Ming", code: "#AG9892" },
    distributor: { name: "Marcus Lim", code: "#DS0871" },
    bank: {
      name: "Vietcombank",
      logoUrl: "https://placehold.co/24x24?text=VCB",
      swift: "BFTVVNVX",
      accountName: "Pham Global",
      accountNumber: "0071-000-228811",
    },
  },
];

// --- Affiliate members (admin affiliate view) ---

export const AFFILIATES: Distributor[] = [
  {
    id: "#AG8932",
    name: "Sarah Chen",
    email: "sarah.chen@aimearn.com",
    countries: ["SG"],
    affiliateMembers: 240,
    joined: "2026-01-12",
    totalOrders: 2140,
    totalSales: "$142,780",
    commissionPool: "$14,278",
    directCommission: "$7,100",
    indirectCommission: "$3,200",
    totalEarnings: "$10,300",
    status: "active",
    inviter: { name: "Alexa Microsoft", code: "#BB5252" },
    distributor: { name: "Dana Wong", code: "#DS1024" },
    bank: {
      name: "DBS Bank",
      logoUrl: "https://placehold.co/24x24?text=DBS",
      swift: "DBSSSGSG",
      accountName: "Sarah Chen",
      accountNumber: "123-456-7890",
    },
  },
  {
    id: "#AG3761",
    name: "Anan Suksan",
    email: "anan.suksan@aimearn.com",
    countries: ["TH"],
    affiliateMembers: 198,
    joined: "2026-01-22",
    totalOrders: 1875,
    totalSales: "$112,300",
    commissionPool: "$11,230",
    directCommission: "$5,600",
    indirectCommission: "$2,500",
    totalEarnings: "$8,100",
    status: "active",
    inviter: { name: "Sarah Chen", code: "#AG8932" },
    distributor: { name: "Marcus Lim", code: "#DS0871" },
    bank: {
      name: "Bangkok Bank",
      logoUrl: "https://placehold.co/24x24?text=BBL",
      swift: "BKKBTHBK",
      accountName: "Anan Suksan",
      accountNumber: "201-554-8821",
    },
  },
  {
    id: "#AG6145",
    name: "Nur Aisyah",
    email: "nur.aisyah@aimearn.com",
    countries: ["MY"],
    affiliateMembers: 164,
    joined: "2026-02-03",
    totalOrders: 1640,
    totalSales: "$89,420",
    commissionPool: "$8,942",
    directCommission: "$4,470",
    indirectCommission: "$2,000",
    totalEarnings: "$6,470",
    status: "active",
    inviter: { name: "Anan Suksan", code: "#AG3761" },
    distributor: { name: "Priya Shah", code: "#DS0612" },
    bank: {
      name: "CIMB",
      logoUrl: "https://placehold.co/24x24?text=CIMB",
      swift: "CIBBMYKL",
      accountName: "Nur Aisyah",
      accountNumber: "7012-4455-6677",
    },
  },
  {
    id: "#AG9892",
    name: "Wei Ming",
    email: "wei.ming@aimearn.com",
    countries: ["SG"],
    affiliateMembers: 120,
    joined: "2026-02-18",
    totalOrders: 1210,
    totalSales: "$62,850",
    commissionPool: "$6,285",
    directCommission: "$3,140",
    indirectCommission: "$1,420",
    totalEarnings: "$4,560",
    status: "inactive",
    inviter: { name: "Nur Aisyah", code: "#AG6145" },
    distributor: { name: "Haruto Sato", code: "#DS0455" },
    bank: {
      name: "OCBC Bank",
      logoUrl: "https://placehold.co/24x24?text=OCBC",
      swift: "OCBCSGSG",
      accountName: "Wei Ming",
      accountNumber: "555-773-2210",
    },
  },
  {
    id: "#AG9735",
    name: "Zhi Hao",
    email: "zhi.hao@aimearn.com",
    countries: ["SG"],
    affiliateMembers: 86,
    joined: "2026-03-01",
    totalOrders: 860,
    totalSales: "$48,120",
    commissionPool: "$4,812",
    directCommission: "$2,400",
    indirectCommission: "$1,080",
    totalEarnings: "$3,480",
    status: "inactive",
    inviter: { name: "Wei Ming", code: "#AG9892" },
    distributor: { name: "Lena Pham", code: "#DS0339" },
    bank: {
      name: "UOB",
      logoUrl: "https://placehold.co/24x24?text=UOB",
      swift: "UOVBSGSG",
      accountName: "Zhi Hao",
      accountNumber: "888-123-4567",
    },
  },
];

// --- Brands (admin brands view) ---

export const BRANDS: Brand[] = [
  {
    id: "BR-001",
    name: "StellarTech",
    logoUrl: "https://placehold.co/104x104?text=ST",
    website: "https://stellartech.example.com",
    products: 24,
    totalSales: 1_250_000,
    totalCommission: 125_000,
    countries: ["SG", "MY", "TH", "ID"],
    status: "active",
    updatedBy: "Morgan Lee",
    updatedDate: "2026-03-20",
    contact: {
      name: "Alex Johnson",
      position: "Manager",
      email: "alex.johnson@stellatech.com",
      phone: "(555) 123-4567",
    },
  },
  {
    id: "BR-002",
    name: "AquaSound",
    logoUrl: "https://placehold.co/104x104?text=AQ",
    website: "https://aquasound.example.com",
    products: 18,
    totalSales: 820_000,
    totalCommission: 82_000,
    countries: ["TH", "VN"],
    status: "active",
    updatedBy: "Morgan Lee",
    updatedDate: "2026-03-18",
    contact: {
      name: "Noah Rivera",
      position: "Director",
      email: "noah.rivera@aquasound.com",
      phone: "(555) 224-8971",
    },
  },
  {
    id: "BR-003",
    name: "Nimbus",
    logoUrl: "https://placehold.co/104x104?text=NB",
    website: "https://nimbus.example.com",
    products: 11,
    totalSales: 430_000,
    totalCommission: 43_000,
    countries: ["MY"],
    status: "inactive",
    updatedBy: "Dana Wong",
    updatedDate: "2026-02-27",
    contact: {
      name: "Mei Lin",
      position: "Brand Manager",
      email: "mei.lin@nimbus.com",
      phone: "(555) 771-4402",
    },
  },
  {
    id: "BR-004",
    name: "Orbit",
    logoUrl: "https://placehold.co/104x104?text=OR",
    website: "https://orbit.example.com",
    products: 9,
    totalSales: 92_000,
    totalCommission: 9_200,
    countries: ["SG", "PH"],
    status: "active",
    updatedBy: "Priya Shah",
    updatedDate: "2026-02-14",
    contact: {
      name: "Haruto Sato",
      position: "Product Lead",
      email: "haruto.sato@orbit.com",
      phone: "(555) 349-7712",
    },
  },
  {
    id: "BR-005",
    name: "VitaSpring",
    logoUrl: "https://placehold.co/104x104?text=VS",
    website: "https://vitaspring.example.com",
    products: 6,
    totalSales: 48_000,
    totalCommission: 4_800,
    countries: ["ID"],
    status: "inactive",
    updatedBy: "Lena Pham",
    updatedDate: "2026-01-30",
    contact: {
      name: "Grace Lau",
      position: "Account Manager",
      email: "grace.lau@vitaspring.com",
      phone: "(555) 908-1123",
    },
  },
];

// --- Users ---

export const USERS: User[] = [
  {
    profileImageURL: "https://i.pravatar.cc/128?img=12",
    email: "distributor@example.com",
    firstName: "Dana",
    lastName: "Wong",
    countries: ["SG", "MY", "TH"],
    role: "distributor",
    status: "APPROVED",
  },
  {
    profileImageURL: "https://i.pravatar.cc/128?img=15",
    email: "pending-distributor@example.com",
    firstName: "Chris",
    lastName: "Tan",
    countries: ["SG"],
    role: "distributor",
    status: "PENDING",
  },
  {
    profileImageURL: "https://i.pravatar.cc/128?img=32",
    email: "affiliate@example.com",
    firstName: "Alex",
    lastName: "Nguyen",
    countries: ["SG"],
    role: "affiliate",
  },
  {
    profileImageURL: "https://i.pravatar.cc/128?img=5",
    email: "admin@example.com",
    firstName: "Morgan",
    lastName: "Lee",
    countries: null,
    role: "admin",
  },
];

// --- Brand products (admin/brands/[id] Products tab) ---

export const BRAND_PRODUCTS: BrandProduct[] = [
  {
    sku: "SKU-HEADPHONE-001",
    name: "Quantum Pro X",
    price: "$23.99",
    thumbnail: "https://placehold.co/64x64?text=QP",
    countries: ["SG", "TH", "MY", "ID"],
    status: "active",
  },
  {
    sku: "SKU-HEADPHONE-002",
    name: "NovaTech Ultra",
    price: "$19.50",
    thumbnail: "https://placehold.co/64x64?text=NT",
    countries: ["SG"],
    status: "active",
  },
  {
    sku: "SKU-HEADPHONE-003",
    name: "Apex Prime Elite",
    price: "$45.00",
    thumbnail: "https://placehold.co/64x64?text=AP",
    countries: ["SG"],
    status: "active",
  },
  {
    sku: "SKU-HEADPHONE-004",
    name: "Zenith Max Plus",
    price: "$120.00",
    thumbnail: "https://placehold.co/64x64?text=ZM",
    countries: ["SG"],
    status: "active",
  },
  {
    sku: "SKU-HEADPHONE-005",
    name: "Stellar Edge Pro",
    price: "$77.50",
    thumbnail: "https://placehold.co/64x64?text=SE",
    countries: ["SG"],
    status: "active",
  },
  {
    sku: "SKU-HEADPHONE-006",
    name: "Fusion Core X",
    price: "$240.00",
    thumbnail: "https://placehold.co/64x64?text=FC",
    countries: ["SG"],
    status: "active",
  },
  {
    sku: "SKU-HEADPHONE-007",
    name: "Velocity Prime Max",
    price: "$99.99",
    thumbnail: "https://placehold.co/64x64?text=VP",
    countries: ["SG"],
    status: "active",
  },
  {
    sku: "SKU-HEADPHONE-008",
    name: "Titan Edge Ultra",
    price: "$14.00",
    thumbnail: "https://placehold.co/64x64?text=TE",
    countries: ["SG"],
    status: "active",
  },
  {
    sku: "SKU-HEADPHONE-009",
    name: "Omega Pro Elite",
    price: "$150.50",
    thumbnail: "https://placehold.co/64x64?text=OP",
    countries: ["SG"],
    status: "inactive",
  },
  {
    sku: "SKU-HEADPHONE-010",
    name: "Aurora Max Plus",
    price: "$300.00",
    thumbnail: "https://placehold.co/64x64?text=AM",
    countries: ["SG"],
    status: "active",
  },
];

// --- Payouts (admin/payout) ---

export const PAYOUT_STATUS_CONFIG: Record<
  PayoutStatus,
  { label: string; dotColor: string }
> = {
  paid: { label: "Paid", dotColor: "#51C712" },
  processing: { label: "Processing", dotColor: "#FFC300" },
};

export const PAYOUT_STATUS_OPTIONS = [
  { label: "All", value: "all" },
  { label: "Paid", value: "paid" },
  { label: "Processing", value: "processing" },
];

export const PAYOUT_SORT_OPTIONS = [
  { label: "Net Payout (High to Low)", value: "net-desc" },
  { label: "Net Payout (Low to High)", value: "net-asc" },
  { label: "Total Orders", value: "orders" },
  { label: "Name (A–Z)", value: "name" },
];

export const PAYOUT_GROUPS: PayoutGroup[] = [
  {
    country: "SG",
    affiliates: [
      {
        name: "Theresa Webb",
        code: "#AG8932",
        country: "SG",
        totalOrders: 90,
        totalSales: "$100,000",
        totalCommission: "$15,200",
        ownCommission: "$15,200",
        overridingCommission: "$15,200",
        netPayout: "$15,155",
        bankAccount: "148-X-XXXX2-1",
        bankName: "Kasikorn",
      },
      {
        name: "Jenny Wilson",
        code: "#AG3761",
        country: "SG",
        totalOrders: 90,
        totalSales: "$100,000",
        totalCommission: "$4,100",
        ownCommission: "$4,100",
        overridingCommission: "$4,100",
        netPayout: "$4,095",
        bankAccount: "148-X-XXXX2-1",
        bankName: "Kasikorn",
      },
      {
        name: "Ralph Edwards",
        code: "#AG6145",
        country: "SG",
        totalOrders: 90,
        totalSales: "$100,000",
        totalCommission: "$1,100",
        ownCommission: "$1,100",
        overridingCommission: "$1,100",
        netPayout: "$1,095",
        bankAccount: "148-X-XXXX2-1",
        bankName: "Kasikorn",
      },
      {
        name: "Marvin McKinney",
        code: "#AG9892",
        country: "SG",
        totalOrders: 90,
        totalSales: "$100,000",
        totalCommission: "$30",
        ownCommission: "$30",
        overridingCommission: "$30",
        netPayout: "$25",
        bankAccount: "148-X-XXXX2-1",
        bankName: "Kasikorn",
      },
      {
        name: "Brooklyn Simmons",
        code: "#AG9735",
        country: "SG",
        totalOrders: 90,
        totalSales: "$100,000",
        totalCommission: "$1,100",
        ownCommission: "$1,100",
        overridingCommission: "$1,100",
        netPayout: "$1,095",
        bankAccount: "148-X-XXXX2-1",
        bankName: "Kasikorn",
      },
    ],
  },
  {
    country: "TH",
    affiliates: [
      {
        name: "Kristin Watson",
        code: "#AG6314",
        country: "TH",
        totalOrders: 90,
        totalSales: "$100,000",
        totalCommission: "$4,100",
        ownCommission: "$4,100",
        overridingCommission: "$4,100",
        netPayout: "$30",
        bankAccount: "148-X-XXXX2-1",
        bankName: "Kasikorn",
      },
      {
        name: "Esther Howard",
        code: "#AG9359",
        country: "TH",
        totalOrders: 90,
        totalSales: "$100,000",
        totalCommission: "$1,100",
        ownCommission: "$1,100",
        overridingCommission: "$1,100",
        netPayout: "$30",
        bankAccount: "148-X-XXXX2-1",
        bankName: "Kasikorn",
      },
      {
        name: "Darlene Robertson",
        code: "#AG2497",
        country: "TH",
        totalOrders: 90,
        totalSales: "$100,000",
        totalCommission: "$30",
        ownCommission: "$30",
        overridingCommission: "$30",
        netPayout: "$30",
        bankAccount: "148-X-XXXX2-1",
        bankName: "Kasikorn",
      },
      {
        name: "Leslie Alexander",
        code: "#AG4828",
        country: "TH",
        totalOrders: 90,
        totalSales: "$100,000",
        totalCommission: "$1,100",
        ownCommission: "$1,100",
        overridingCommission: "$1,100",
        netPayout: "$30",
        bankAccount: "148-X-XXXX2-1",
        bankName: "Kasikorn",
      },
    ],
  },
];

export const PAYOUT_AFFILIATES: Record<string, PayoutAffiliateSummary> = {
  "#AG8932": {
    code: "#AG8932",
    name: "Theresa Webb",
    country: "SG",
    totalOrders: 190,
    totalSales: "$200,000",
    totalCommission: "$7,200",
    ownCommission: "$2,000",
    overridingCommission: "$5,200",
    orders: [
      {
        id: "#OR8932",
        orderedDate: "2026-01-12",
        referralMemberName: "Theresa Webb",
        referralMemberCode: "#AG8932",
        customerName: "Theresa Webb",
        customerCode: "#CM8932",
        brandName: "AquaGlow",
        brandCode: "#BD8932",
        totalSales: "$15,200",
        totalCommission: "$5,200",
        ownCommission: "",
        overridingCommission: "$5,200",
        shippingStatus: "shipped",
      },
      {
        id: "#OR3761",
        orderedDate: "2026-01-01",
        referralMemberName: "Theresa Webb",
        referralMemberCode: "#AG8932",
        customerName: "Jenny Wilson",
        customerCode: "#CM3761",
        brandName: "BloomBeauty",
        brandCode: "#BD3761",
        totalSales: "$4,100",
        totalCommission: "$400",
        ownCommission: "",
        overridingCommission: "$400",
        shippingStatus: "shipped",
      },
      {
        id: "#OR6145",
        orderedDate: "2025-12-15",
        referralMemberName: "Jenny Wilson",
        referralMemberCode: "#AG8932",
        customerName: "Ralph Edwards",
        customerCode: "#CM6145",
        brandName: "Evergreen Goods",
        brandCode: "#BD6145",
        totalSales: "$1,100",
        totalCommission: "$100",
        ownCommission: "",
        overridingCommission: "- $100",
        overridingNegative: true,
        shippingStatus: "refunded",
      },
      {
        id: "#OR9892",
        orderedDate: "2025-11-03",
        referralMemberName: "Jenny Wilson",
        referralMemberCode: "#AG8932",
        customerName: "Marvin McKinney",
        customerCode: "#CM9892",
        brandName: "NovaStyle",
        brandCode: "#BD9892",
        totalSales: "$30",
        totalCommission: "$3",
        ownCommission: "",
        overridingCommission: "$3",
        shippingStatus: "shipped",
      },
      {
        id: "#OR9735",
        orderedDate: "2025-10-22",
        referralMemberName: "Jenny Wilson",
        referralMemberCode: "#AG8932",
        customerName: "Brooklyn Simmons",
        customerCode: "#CM9735",
        brandName: "Urban Luxe",
        brandCode: "#BD9735",
        totalSales: "$1,100",
        totalCommission: "$100",
        ownCommission: "",
        overridingCommission: "$100",
        shippingStatus: "shipped",
      },
      {
        id: "#OR4719",
        orderedDate: "2025-09-07",
        referralMemberName: "Jenny Wilson",
        referralMemberCode: "#AG8932",
        customerName: "Albert Flores",
        customerCode: "#CM4719",
        brandName: "Zenith Emporium",
        brandCode: "#BD4719",
        totalSales: "$1,100",
        totalCommission: "$100",
        ownCommission: "",
        overridingCommission: "$100",
        shippingStatus: "shipped",
      },
      {
        id: "#OR6314",
        orderedDate: "2025-08-18",
        referralMemberName: "Theresa Webb",
        referralMemberCode: "#AG8932",
        customerName: "Kristin Watson",
        customerCode: "#CM6314",
        brandName: "Veridian Dynamics",
        brandCode: "#BD6314",
        totalSales: "$30",
        totalCommission: "$3",
        ownCommission: "$3",
        overridingCommission: "",
        shippingStatus: "shipped",
      },
      {
        id: "#OR9359",
        orderedDate: "2025-08-18",
        referralMemberName: "Theresa Webb",
        referralMemberCode: "#AG8932",
        customerName: "Esther Howard",
        customerCode: "#CM9359",
        brandName: "Celestial Artisans",
        brandCode: "#BD9359",
        totalSales: "$30",
        totalCommission: "$3",
        ownCommission: "$3",
        overridingCommission: "",
        shippingStatus: "shipped",
      },
      {
        id: "#OR2497",
        orderedDate: "2025-07-30",
        referralMemberName: "Theresa Webb",
        referralMemberCode: "#AG8932",
        customerName: "Darlene Robertson",
        customerCode: "#CM2497",
        brandName: "Aurora Outfitters",
        brandCode: "#BD2497",
        totalSales: "$30",
        totalCommission: "$3",
        ownCommission: "$3",
        overridingCommission: "",
        shippingStatus: "shipped",
      },
      {
        id: "#OR4828",
        orderedDate: "2025-07-30",
        referralMemberName: "Theresa Webb",
        referralMemberCode: "#AG8932",
        customerName: "Leslie Alexander",
        customerCode: "#CM4828",
        brandName: "Summit Retail",
        brandCode: "#BD4828",
        totalSales: "$30",
        totalCommission: "$3",
        ownCommission: "$3",
        overridingCommission: "",
        shippingStatus: "shipped",
      },
    ],
  },
};

export const PAYOUTS: Payout[] = [
  {
    id: "PO-202601",
    circle: "1 - 31 Jan 2026",
    payoutDate: "",
    orders: 340,
    affiliates: 340,
    transactionFee: "$18,400",
    totalAmount: "$18,400",
    status: "processing",
  },
  {
    id: "PO-202601A",
    circle: "1 - 15 Jan 2026",
    payoutDate: "2026-01-15",
    orders: 200,
    affiliates: 200,
    transactionFee: "$6,700",
    totalAmount: "$6,700",
    status: "paid",
  },
  {
    id: "PO-202512B",
    circle: "16 - 31 Dec 2025",
    payoutDate: "2025-12-16",
    orders: 150,
    affiliates: 150,
    transactionFee: "$2,300",
    totalAmount: "$2,300",
    status: "paid",
  },
  {
    id: "PO-202512A",
    circle: "1 - 15 Dec 2025",
    payoutDate: "2025-11-03",
    orders: 100,
    affiliates: 100,
    transactionFee: "$2,300",
    totalAmount: "$2,300",
    status: "paid",
  },
  {
    id: "PO-202511B",
    circle: "16 - 30 Nov 2025",
    payoutDate: "2025-10-22",
    orders: 89,
    affiliates: 89,
    transactionFee: "$2,300",
    totalAmount: "$2,300",
    status: "paid",
  },
  {
    id: "PO-202511A",
    circle: "1 - 15 Nov 2025",
    payoutDate: "2025-09-07",
    orders: 53,
    affiliates: 53,
    transactionFee: "$2,300",
    totalAmount: "$2,300",
    status: "paid",
  },
  {
    id: "PO-202510B",
    circle: "16 - 31 Oct 2025",
    payoutDate: "2025-08-18",
    orders: 40,
    affiliates: 40,
    transactionFee: "$2,300",
    totalAmount: "$2,300",
    status: "paid",
  },
  {
    id: "PO-202510A",
    circle: "1 - 15 Oct 2025",
    payoutDate: "2025-08-18",
    orders: 20,
    affiliates: 20,
    transactionFee: "$2,300",
    totalAmount: "$2,300",
    status: "paid",
  },
  {
    id: "PO-202509B",
    circle: "16 - 30 Sep 2025",
    payoutDate: "2025-07-30",
    orders: 20,
    affiliates: 20,
    transactionFee: "$2,300",
    totalAmount: "$2,300",
    status: "paid",
  },
  {
    id: "PO-202509A",
    circle: "1 - 15 Sep 2025",
    payoutDate: "2025-07-30",
    orders: 20,
    affiliates: 20,
    transactionFee: "$2,300",
    totalAmount: "$2,300",
    status: "paid",
  },
];

// --- Admin user management (admin/user/roles, admin/user/users) ---

export const ADMIN_ROLES: AdminRole[] = [
  {
    id: "RL-001",
    name: "Admin",
    status: "active",
    lastUpdated: "2026-01-12",
  },
  {
    id: "RL-002",
    name: "User",
    status: "active",
    lastUpdated: "2026-01-01",
  },
];

export const ADMIN_USERS: AdminUser[] = [
  {
    id: "US-001",
    firstName: "Alex",
    lastName: "Johnson",
    email: "steve@example.com",
    role: "Admin",
    status: "active",
  },
  {
    id: "US-002",
    firstName: "Emily",
    lastName: "Carter",
    email: "linus@example.com",
    role: "Admin",
    status: "active",
  },
  {
    id: "US-003",
    firstName: "Michael",
    lastName: "Smith",
    email: "jason@example.com",
    role: "Admin",
    status: "active",
  },
  {
    id: "US-004",
    firstName: "David",
    lastName: "Wilson",
    email: "maria@example.com",
    role: "Admin",
    status: "active",
  },
  {
    id: "US-005",
    firstName: "Jessica",
    lastName: "Taylor",
    email: "anna@example.com",
    role: "Admin",
    status: "active",
  },
  {
    id: "US-006",
    firstName: "Daniel",
    lastName: "Lee",
    email: "tom@example.com",
    role: "Admin",
    status: "active",
  },
  {
    id: "US-007",
    firstName: "Olivia",
    lastName: "Martinez",
    email: "lucas@example.com",
    role: "Admin",
    status: "active",
  },
  {
    id: "US-008",
    firstName: "Sophia",
    lastName: "Brown",
    email: "sophia@example.com",
    role: "Admin",
    status: "active",
  },
  {
    id: "US-009",
    firstName: "James",
    lastName: "Davis",
    email: "noah@example.com",
    role: "Admin",
    status: "active",
  },
  {
    id: "US-010",
    firstName: "Isabella",
    lastName: "Garcia",
    email: "ella@example.com",
    role: "Admin",
    status: "active",
  },
];

// --- Announcements (admin/announcement) ---

export const ANNOUNCEMENT_STATUS_CONFIG: Record<
  AnnouncementStatus,
  { label: string; dotColor: string }
> = {
  published: { label: "Published", dotColor: "#51C712" },
  upcoming: { label: "Upcoming", dotColor: "#00A1FF" },
  draft: { label: "Draft", dotColor: "#FFC300" },
};

export const ANNOUNCEMENT_STATUS_OPTIONS = [
  { label: "All", value: "all" },
  { label: "Published", value: "published" },
  { label: "Upcoming", value: "upcoming" },
  { label: "Draft", value: "draft" },
];

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: "AN-001",
    title: "Thank you for purchase",
    targetAudience: "Thank you for purchase",
    publishDate: "2026-01-12",
    status: "published",
    createdBy: "Bessie Cooper",
    createdDate: "2026-01-12",
  },
  {
    id: "AN-002",
    title: "Invitation",
    targetAudience: "Invitation",
    publishDate: "2026-01-01",
    status: "upcoming",
    createdBy: "Marvin McKinney",
    createdDate: "2026-01-01",
  },
  {
    id: "AN-003",
    title: "Affiliate non Active",
    targetAudience: "Affiliate non Active",
    publishDate: "2025-12-15",
    status: "draft",
    createdBy: "Wade Warren",
    createdDate: "2025-12-15",
  },
];

// --- Setting: Countries (admin/setting/country) ---

export const COUNTRY_CONFIGS: CountryConfig[] = [
  { id: "C-001", name: "Singapore", currency: "SGD", exchangeRate: "$1 = $35", code: "SG", distributorFee: "$10,000", status: "active" },
  { id: "C-002", name: "Thailand", currency: "THB", exchangeRate: "$1 = $35", code: "SG", distributorFee: "$10,000", status: "active" },
  { id: "C-003", name: "Malaysia", currency: "MYR", exchangeRate: "$1 = $35", code: "SG", distributorFee: "$10,000", status: "active" },
  { id: "C-004", name: "India", currency: "INR", exchangeRate: "$1 = $35", code: "SG", distributorFee: "$10,000", status: "active" },
  { id: "C-005", name: "China", currency: "CNY", exchangeRate: "$1 = $35", code: "SG", distributorFee: "$10,000", status: "active" },
  { id: "C-006", name: "Japan", currency: "JPY", exchangeRate: "$1 = $35", code: "SG", distributorFee: "$10,000", status: "active" },
  { id: "C-007", name: "Australia", currency: "AUD", exchangeRate: "$1 = $35", code: "SG", distributorFee: "$10,000", status: "active" },
  { id: "C-008", name: "United States", currency: "USD", exchangeRate: "$1 = $35", code: "SG", distributorFee: "$10,000", status: "active" },
  { id: "C-009", name: "Myanmar", currency: "MMK", exchangeRate: "$1 = $35", code: "SG", distributorFee: "$10,000", status: "active" },
  { id: "C-010", name: "Georgia", currency: "GEL", exchangeRate: "$1 = $35", code: "SG", distributorFee: "$10,000", status: "active" },
];

// --- Setting: Banks (admin/setting/bank) ---

export const BANK_CONFIGS: BankConfig[] = [
  { id: "B-0005", name: "Evergreen Bank", code: "0005", country: "Singapore", currency: "SGD", status: "active" },
  { id: "B-0007", name: "Golden Summit", code: "0007", country: "Singapore", currency: "SGD", status: "active" },
  { id: "B-0006", name: "Pinnacle Trust", code: "0006", country: "Singapore", currency: "SGD", status: "active" },
  { id: "B-0008", name: "Azure Holdings", code: "0008", country: "India", currency: "INR", status: "active" },
  { id: "B-0009", name: "Crimson Capital", code: "0009", country: "China", currency: "CNY", status: "active" },
  { id: "B-0010", name: "Obsidian Financial", code: "0010", country: "Japan", currency: "JPY", status: "active" },
  { id: "B-0011", name: "Veridian Credit", code: "0011", country: "Australia", currency: "AUD", status: "active" },
  { id: "B-0012", name: "Silver Stream", code: "0012", country: "United States", currency: "USD", status: "active" },
  { id: "B-0013", name: "Bronze Bridge", code: "0013", country: "Myanmar", currency: "MMK", status: "active" },
  { id: "B-0014", name: "Ivory Investments", code: "0014", country: "Georgia", currency: "GEL", status: "active" },
];
